// AUTO-GENERATED by scripts/genabi.mjs -- do not edit by hand.
// Populated from contracts/deployments/<chainId>.json after `forge script Deploy`.

export type DeploymentAddresses = {
  vUSD: `0x${string}`;
  attestationOracle: `0x${string}`;
  trustFlowPool: `0x${string}`;
  cvaPolicy: `0x${string}`;
  oracleMode: string;
};

export const generatedDeployments: Record<number, DeploymentAddresses> = {
  "10143": {
    "vUSD": "0x3C45E7451fB59E59a6d94628112F6D4Ada2bd9Ba",
    "attestationOracle": "0x69e0F1E783661ae6EB65eD56CfA3AD2F9C38ad87",
    "trustFlowPool": "0x3d48509923483B17F9Fb46F1ceDb01FfDa5311Bd",
    "cvaPolicy": "0x7580182fd993175C04F35580d5418b71Bb943c1e",
    "oracleMode": "mock"
  },
  "31337": {
    "vUSD": "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
    "attestationOracle": "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
    "trustFlowPool": "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
    "cvaPolicy": "0x9A676e781A523b5d0C0e43731313A708CB607508",
    "oracleMode": "mock"
  }
};
