#!/usr/bin/env node
/**
 * Regenerates `src/lib/abis.ts` from the Foundry build artifacts, and
 * `src/lib/deployments.generated.ts` from `contracts/deployments/*.json`.
 *
 * Run via `npm run genabi` (or the root `make abi`) after any contract change, so the
 * frontend can never drift from what is actually deployed.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB = resolve(__dirname, "..");
const CONTRACTS = resolve(WEB, "..", "contracts");
const OUT = join(CONTRACTS, "out");
const DEPLOYMENTS = join(CONTRACTS, "deployments");

const CONTRACT_FILES = {
  trustFlowPoolAbi: "TrustFlowPool.sol/TrustFlowPool.json",
  attestationOracleAbi: "MockAttestationOracle.sol/MockAttestationOracle.json",
  cvaStablecoinAbi: "CVAStablecoin.sol/CVAStablecoin.json",
  cvaPolicyAbi: "CVACompliancePolicy.sol/CVACompliancePolicy.json",
};

function loadAbi(relPath) {
  const full = join(OUT, relPath);
  if (!existsSync(full)) {
    console.error(`\n  Missing artifact: ${full}`);
    console.error("  Run `forge build` in ../contracts first.\n");
    process.exit(1);
  }
  return JSON.parse(readFileSync(full, "utf8")).abi;
}

// ---------------------------------------------------------------- ABIs
let abiFile = `// AUTO-GENERATED by scripts/genabi.mjs -- do not edit by hand.
// Regenerate with: npm run genabi

`;

for (const [exportName, relPath] of Object.entries(CONTRACT_FILES)) {
  const abi = loadAbi(relPath);
  abiFile += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

mkdirSync(join(WEB, "src", "lib"), { recursive: true });
writeFileSync(join(WEB, "src", "lib", "abis.ts"), abiFile);
console.log("  wrote src/lib/abis.ts");

// ---------------------------------------------------------- Deployments
const deployments = {};
if (existsSync(DEPLOYMENTS)) {
  for (const file of readdirSync(DEPLOYMENTS)) {
    if (!file.endsWith(".json")) continue;
    const parsed = JSON.parse(readFileSync(join(DEPLOYMENTS, file), "utf8"));
    const chainId = Number(parsed.chainId ?? file.replace(".json", ""));
    deployments[chainId] = {
      vUSD: parsed.vUSD,
      attestationOracle: parsed.attestationOracle,
      trustFlowPool: parsed.trustFlowPool,
      cvaPolicy: parsed.cvaPolicy,
      oracleMode: parsed.oracleMode ?? "mock",
    };
  }
}

const deploymentsFile = `// AUTO-GENERATED by scripts/genabi.mjs -- do not edit by hand.
// Populated from contracts/deployments/<chainId>.json after \`forge script Deploy\`.

export type DeploymentAddresses = {
  vUSD: \`0x\${string}\`;
  attestationOracle: \`0x\${string}\`;
  trustFlowPool: \`0x\${string}\`;
  cvaPolicy: \`0x\${string}\`;
  oracleMode: string;
};

export const generatedDeployments: Record<number, DeploymentAddresses> = ${JSON.stringify(
  deployments,
  null,
  2
)};
`;

writeFileSync(join(WEB, "src", "lib", "deployments.generated.ts"), deploymentsFile);
console.log(
  `  wrote src/lib/deployments.generated.ts (${Object.keys(deployments).length} chain(s))`
);
